apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: "ap-south-1"
    objects: |
      - objectName: "airbnb-secrects"  
        objectType: "secretsmanager"
        jmesPath:
          - path: "PORT"
            objectAlias: "PORT"
          - path: "CLOUD_NAME"
            objectAlias: "CLOUD_NAME"
          - path: "CLOUD_API_KEY"
            objectAlias: "CLOUD_API_KEY"
          - path: "CLOUD_API_SECRET"
            objectAlias: "CLOUD_API_SECRET"
          - path: "ATLASDB_URL"
            objectAlias: "ATLASDB_URL"
          - path: "SECRET"
            objectAlias: "SECRET"
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: PORT
          key: PORT
        - objectName: CLOUD_NAME
          key: CLOUD_NAME
        - objectName: CLOUD_API_KEY
          key: CLOUD_API_KEY
        - objectName: CLOUD_API_SECRET
          key: CLOUD_API_SECRET
        - objectName: ATLASDB_URL
          key: ATLASDB_URL
        - objectName: SECRET
          key: SECRET
